<RockSimDocument>
<FileVersion>4</FileVersion>
<DesignInformation>
<RocketDesign>
<Name>RORO1</Name>
<CalculateCD>1</CalculateCD>
<ProCalculateCD>1</ProCalculateCD>
<ProCalculateCN>1</ProCalculateCN>
<FixedCd>0.75</FixedCd>
<FixedCd2>0.8</FixedCd2>
<FixedCd3>0.81</FixedCd3>
<FixedCd2Alone>0.95</FixedCd2Alone>
<FixedCd3Alone>0.95</FixedCd3Alone>
<StageCount>1</StageCount>
<Stage3Mass>0.</Stage3Mass>
<Stage2Mass>0.</Stage2Mass>
<Stage1Mass>0.</Stage1Mass>
<Stage321CG>0.</Stage321CG>
<Stage32CG>0.</Stage32CG>
<Stage3CG>0.</Stage3CG>
<Stage2CGAlone>0.</Stage2CGAlone>
<Stage1CGAlone>0.</Stage1CGAlone>
<CPCalcFlags>1</CPCalcFlags>
<LaunchGuideLength>914.4</LaunchGuideLength>
<UseKnownMass>0</UseKnownMass>
<DefaultFinish>0</DefaultFinish>
<FinishMedium>0</FinishMedium>
<FinishCoatCount>1</FinishCoatCount>
<GlueType>0</GlueType>
<CPSimFlags>1</CPSimFlags>
<LastSerialNumber>18</LastSerialNumber>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<CameraState>CSV1|1|0,0,0|0,0,1|0,1,0|0.01,1000.01|30|2|1|0|0|0|0|0</CameraState>
<BarromanXN>0,1662.81,0,0</BarromanXN>
<BarrowmanCNa>0,5.13257,0,0</BarrowmanCNa>
<RockSimXN>0,1926.06,0,0</RockSimXN>
<RockSimCNa>0,7.31986,0,0</RockSimCNa>
<RockSimCNa90>0,0,0,0</RockSimCNa90>
<RockSimXN90>0,0,0,0</RockSimXN90>
<ViewType>0</ViewType>
<ViewStageCount>1</ViewStageCount>
<ViewTypeEdit>0</ViewTypeEdit>
<ViewStageCountEdit>1</ViewStageCountEdit>
<ZoomFactor>0.</ZoomFactor>
<ZoomFactorEdit>0.</ZoomFactorEdit>
<ScrollPosX>0</ScrollPosX>
<ScrollPosY>0</ScrollPosY>
<ScrollPosXEdit>0</ScrollPosXEdit>
<ScrollPosYEdit>0</ScrollPosYEdit>
<ThreeDFlags>0</ThreeDFlags>
<ThreeDFlagsEdit>0</ThreeDFlagsEdit>
<UseModelSprite>0</UseModelSprite>
<StaticMarginRef>0</StaticMarginRef>
<UserRefDiameter>0.</UserRefDiameter>
<SideMarkerHeight>10.</SideMarkerHeight>
<SideDimensionHeight>10.</SideDimensionHeight>
<BaseMarkerHeight>10.</BaseMarkerHeight>
<BaseDimensionHeight>10.</BaseDimensionHeight>
<ShowGlideCP>0</ShowGlideCP>
<ShowGridTypeSide>0</ShowGridTypeSide>
<ShowGridTypeBase>0</ShowGridTypeBase>
<GridSpacing>10.</GridSpacing>
<GridOpacity>0.15</GridOpacity>
<GridColor>black</GridColor>
<MaxDiaWithFins>356.46</MaxDiaWithFins>
<MaxDiaWithoutFins>156.46</MaxDiaWithoutFins>
<MaxLenWithFins>2659.6</MaxLenWithFins>
<MaxLenWithoutFins>2659.6</MaxLenWithoutFins>
<MinXExtent>0.</MinXExtent>
<MaxXExtent>2659.6</MaxXExtent>
<CalculatedMaxStageDia>0,156.46,0,0</CalculatedMaxStageDia>
<CalculatedStageLen>0,2659.6,0,0</CalculatedStageLen>
<Cd3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd3>
<Cd32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd32>
<Cd321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd321>
<Cb3>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb3>
<Cb32>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb32>
<Cb321>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb321>
<CNa3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa3>
<CNa32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa32>
<CNa321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa321>
<CP3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP3>
<CP32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP32>
<CP321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP321>
<SimulationEventList>
<SimulationEvent>
<PartSerialNo>16</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEventList>
<Stage3Parts>
<NoseCone>
<PartMfg>Public Missiles</PartMfg>
<KnownMass>2300.</KnownMass>
<Density>128.148</Density>
<Material>Fiberglass</Material>
<Name>Nose cone</Name>
<KnownCG>450.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>104.436</CalcMass>
<CalcCG>453.605</CalcCG>
<WettedSurface>0.199728</WettedSurface>
<PaintedSurface>0.199728</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>FNC-6.00</PartNo>
<PartDesc>Fiberglass nose cone</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>1</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>2.</BarrowmanCNa>
<BarrowmanXN>0.282984</BarrowmanXN>
<RockSimCNa>2.</RockSimCNa>
<RockSimXN>0.282984</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>0.</Station>
<Len>609.6</Len>
<BaseDia>154.94</BaseDia>
<FinishCode>0</FinishCode>
<ShapeCode>1</ShapeCode>
<ConstructionType>1</ConstructionType>
<ShoulderLen>100.</ShoulderLen>
<WallThickness>3.17</WallThickness>
<ShapeParameter>4.2</ShapeParameter>
<ShoulderOD>151.64</ShoulderOD>
<BaseExtensionLen>0.</BaseExtensionLen>
<CoreDia>0.</CoreDia>
<CoreLen>0.</CoreLen>
<AttachedParts>
</AttachedParts>
</NoseCone>
<BodyTube>
<PartMfg>Public Missiles Ltd.</PartMfg>
<KnownMass>2000.</KnownMass>
<Density>958.705</Density>
<Material>Kraft phenolic</Material>
<Name>upper tube</Name>
<KnownCG>575.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>1019.79</CalcMass>
<CalcCG>575.</CalcCG>
<WettedSurface>0.565264</WettedSurface>
<PaintedSurface>0.565264</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>PT-6.0</PartNo>
<PartDesc>Airframe tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>2</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>609.6</Station>
<OD>156.46</OD>
<ID>152.65</ID>
<Len>1150.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>Public Missiles</PartMfg>
<KnownMass>400.</KnownMass>
<Density>680.785</Density>
<Material>Birch</Material>
<Name>Bulkhead</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>550.</Xb>
<CalcMass>249.186</CalcMass>
<CalcCG>10.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>BP-6.0</PartNo>
<PartDesc>Was BP-15</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>3</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1159.6</Station>
<OD>152.65</OD>
<ID>0.</ID>
<Len>20.</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>4000.</KnownMass>
<Density>0.</Density>
<Name>Payload</Name>
<KnownCG>350.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>350.</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>11</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>959.6</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>1000.</KnownMass>
<Density>0.</Density>
<Material>Custom</Material>
<Name>Recovery</Name>
<KnownCG>660.5</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>660.5</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>14</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1270.1</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<Parachute>
<PartMfg>Public Missiles</PartMfg>
<KnownMass>700.</KnownMass>
<Density>0.</Density>
<Material>Rip stop nylon</Material>
<Name>Parachute</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>784.</Xb>
<CalcMass>11.6586</CalcMass>
<CalcCG>152.4</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>PAR-72R</PartNo>
<PartDesc>72 in. nylon</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>16</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1393.6</Station>
<Dia>1828.8</Dia>
<SpillHoleDia>254.</SpillHoleDia>
<SideCount>0</SideCount>
<ShroudLineCount>10</ShroudLineCount>
<Thickness>0.1</Thickness>
<ShroudLineLen>1143.</ShroudLineLen>
<ChuteCount>1</ChuteCount>
<ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
<ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
<DragCoefficient>0.75</DragCoefficient>
<AttachedParts>
</AttachedParts>
</Parachute>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>2000.</KnownMass>
<Density>0.</Density>
<Material>Custom</Material>
<Name>Trim Mass</Name>
<KnownCG>541.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>541.</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>18</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1150.6</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>Public Missiles Ltd.</PartMfg>
<KnownMass>1500.</KnownMass>
<Density>958.705</Density>
<Material>Kraft phenolic</Material>
<Name>lower tube</Name>
<KnownCG>450.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>798.097</CalcMass>
<CalcCG>450.</CalcCG>
<WettedSurface>0.44238</WettedSurface>
<PaintedSurface>0.44238</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>PT-6.0</PartNo>
<PartDesc>Airframe tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>5</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1759.6</Station>
<OD>156.46</OD>
<ID>152.65</ID>
<Len>900.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>Public Missiles Ltd.</PartMfg>
<KnownMass>153.087</KnownMass>
<Density>958.705</Density>
<Material>Kraft phenolic</Material>
<Name>Tube coupler</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-100.</Xb>
<CalcMass>263.352</CalcMass>
<CalcCG>152.4</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>CT-6.00</PartNo>
<PartDesc>Coupler tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>6</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1659.6</Station>
<OD>152.65</OD>
<ID>148.844</ID>
<Len>304.8</Len>
<FinishCode>0</FinishCode>
<UsageCode>4</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<BodyTube>
<PartMfg>Public Missiles Ltd.</PartMfg>
<KnownMass>310.</KnownMass>
<Density>958.705</Density>
<Material>Kraft phenolic</Material>
<Name>motor mount</Name>
<KnownCG>350.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>323.397</CalcMass>
<CalcCG>350.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>PT-3.9</PartNo>
<PartDesc>Airframe tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>7</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1959.6</Station>
<OD>102.11</OD>
<ID>99.06</ID>
<Len>700.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>1</IsMotorMount>
<MotorDia>98.</MotorDia>
<EngineOverhang>12.7</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
</AttachedParts>
</BodyTube>
<Ring>
<PartMfg>Custom</PartMfg>
<KnownMass>0.</KnownMass>
<Density>0.</Density>
<Material>Custom</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>260.35</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>1.5</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>9</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2019.95</Station>
<OD>152.65</OD>
<ID>102.11</ID>
<Len>3.</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>Custom</PartMfg>
<KnownMass>0.</KnownMass>
<Density>0.</Density>
<Material>Custom</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>467.5</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>1.5</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>12</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2227.1</Station>
<OD>152.65</OD>
<ID>102.11</ID>
<Len>3.</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>Public Missiles</PartMfg>
<KnownMass>300.</KnownMass>
<Density>680.785</Density>
<Material>Birch</Material>
<Name>Bulkhead</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>-50.</Xb>
<CalcMass>124.593</CalcMass>
<CalcCG>5.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>13</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1709.6</Station>
<OD>152.65</OD>
<ID>0.</ID>
<Len>10.</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>Public Missiles</PartMfg>
<KnownMass>400.</KnownMass>
<Density>680.785</Density>
<Material>Birch</Material>
<Name>engine assembly</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>10.</Xb>
<CalcMass>367.549</CalcMass>
<CalcCG>14.75</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>17</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2620.1</Station>
<OD>152.65</OD>
<ID>0.</ID>
<Len>29.5</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<FinSet>
<PartMfg>Custom</PartMfg>
<KnownMass>1000.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (Birch)</Material>
<Name>Fin set</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>117.449</CalcMass>
<CalcCG>120.526</CalcCG>
<WettedSurface>0.027</WettedSurface>
<PaintedSurface>0.081</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>10</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>3.13257</BarrowmanCNa>
<BarrowmanXN>2.54377</BarrowmanXN>
<RockSimCNa>5.31986</RockSimCNa>
<RockSimXN>2.54377</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>2459.6</Station>
<FinCount>3</FinCount>
<RootChord>200.</RootChord>
<TipChord>70.</TipChord>
<SemiSpan>100.</SemiSpan>
<MidChordLen>111.316</MidChordLen>
<SweepDistance>113.9</SweepDistance>
<Thickness>4.</Thickness>
<ShapeCode>0</ShapeCode>
<FinishCode>0</FinishCode>
<TipShapeCode>0</TipShapeCode>
<TabLength>0.</TabLength>
<TabDepth>0.</TabDepth>
<TabOffset>0.</TabOffset>
<SweepMode>1</SweepMode>
<SweepAngle>0.349066</SweepAngle>
<RockSimXNPerFin>0.</RockSimXNPerFin>
<RockSimRadialXNPerFin>120.205</RockSimRadialXNPerFin>
<RockSimCNaPerFin>3.07142</RockSimCNaPerFin>
<TaperRatio>0.35</TaperRatio>
<CantAngle>0.</CantAngle>
<CantPivotPoint>0.</CantPivotPoint>
<AttachedParts>
</AttachedParts>
</FinSet>
</AttachedParts>
</BodyTube>
</Stage3Parts>
<Stage2Parts>
</Stage2Parts>
<Stage1Parts>
</Stage1Parts>
<SideViewDims>
</SideViewDims>
<BaseViewDims>
</BaseViewDims>
<VertViewDims>
</VertViewDims>
</RocketDesign>
</DesignInformation>
<SimulationResultsList>
<SimulationResults>
<MaxAltitude>755.99</MaxAltitude>
<MaxVelocity>121.71</MaxVelocity>
<MaxAcceleration>99.1021</MaxAcceleration>
<TimeToApogee>12.83</TimeToApogee>
<OptimalDelay>11.4288</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>5</FinalState>
<TimeToBurnout>1.40125</TimeToBurnout>
<TimeToLanding>0.</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>1.01789</MinLaunchGuideLen>
<MaxVertVelocity>121.708</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>99.0938</MaxVertAcceleration>
<MaxHorzAcceleration>0.015339</MaxHorzAcceleration>
<MaxRange>6.86961</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>760.</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>6.</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[K1999N-None] </SimulationName>
<VelocityAtLaunchGuideEnd>12.7325</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.1625</TimeToFreeFlight>
<TimeToMaxVelocity>1.3525</TimeToMaxVelocity>
<TimeToMaxAcceleration>1.07</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.311</ExecutionTime>
<RangeAtLanding>0.</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>0.</VelocityAtLanding>
<XVelcoityAtLanding>0.</XVelcoityAtLanding>
<YVelocityAtLanding>0.</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>19065.5</Mass0>
<CG0>1476.22</CG0>
<LaterialMOI0>4.58075e+07</LaterialMOI0>
<RadialMOI0>0.053607</RadialMOI0>
<CP0>1662.81</CP0>
<CNA0>5.13257</CNA0>
<SM0>1.20431</SM0>
<GUID>{fb568ea3-aa97-4dca-895e-4b00bc8e6b51}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>16</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>K1999N</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>12.7</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>7</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
</SimulationResultsList>
</RockSimDocument>
